### ISSUE TITLE
Copy existing mento.finance code to new mento-interface repo

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-interface#2]
**Description**
We need to duplicate the existing codebase and copy it into the new mento-interface repository to create the base for the second app instance hosted at app.mento.org. In future, this second instance will be integrated with the updated version of Mento and the legacy instance(mento.finance) will still work with MentoV1. This approach will allow us to test Multi-Collateral Mento once it is deployed and we are in the migration phase. The work to create a new vercel app & connect to the subdomain will be completed separately. The only goal here is to move the code and ensure the app functions as expected.    

**Acceptance Criteria**

- [ ] Mento-interface repo contains the code of the mento.finance app
- [ ] New interface is fully functional and works as expected locally

**Comment by jmrossy** [comment]
Done, we transferred the existing repo instead of copying the code
